#!/bin/sh
BROWSER_PROFILE_DIR=~/.local/share/org.sailfishos/browser/.mozilla
BROWSER_DATA_DIR=/usr/share/sailfish-browser/data

if [ ! -d "$BROWSER_PROFILE_DIR" ]; then
    mkdir -p $BROWSER_PROFILE_DIR
fi

if [ ! -f "$BROWSER_PROFILE_DIR/ua-update.json" -o ! -s "$BROWSER_PROFILE_DIR/ua-update.json" ]; then
    # Remove lines starting with a comment.
    sed  '\|^\s*//|d' $BROWSER_DATA_DIR/ua-update.json.in > "$BROWSER_PROFILE_DIR/ua-update.json"
fi

if [ ! -f "$BROWSER_PROFILE_DIR/prefs.js" ]; then
    cp $BROWSER_DATA_DIR/prefs.js $BROWSER_PROFILE_DIR
else
    while IFS='' read -r line || [[ -n "$line" ]]; do
        prefKey=$(echo "$line" | cut -d "," -f1)
        foundKey=$(grep "$prefKey" $BROWSER_PROFILE_DIR/prefs.js | wc -l)
        if [ $foundKey -eq 0 ]; then
            echo "$line" >> $BROWSER_PROFILE_DIR/prefs.js
        fi
    done < "$BROWSER_DATA_DIR/prefs.js"
fi
