#!/bin/sh
BROWSER_PROFILE_DIR=~/.local/share/org.sailfishos/browser/.mozilla
BROWSER_DATA_DIR=/usr/share/sailfish-browser/data

if [ ! -d "$BROWSER_PROFILE_DIR" ]; then
    mkdir -p $BROWSER_PROFILE_DIR
fi
